In [3]:
using LinearAlgebra

In [4]:
x = rand(Float64, (10,10))

10×10 Matrix{Float64}:
 0.604985   0.428884  0.238462  0.620276  …  0.50948    0.492713   0.979963
 0.900088   0.591134  0.255813  0.704652     0.411978   0.873574   0.141335
 0.450255   0.738823  0.455828  0.314674     0.647906   0.659605   0.537392
 0.517489   0.280581  0.876592  0.652857     0.799227   0.17473    0.909244
 0.942409   0.964582  0.430833  0.402191     0.531224   0.759259   0.325524
 0.908511   0.274292  0.354811  0.784268  …  0.472173   0.0304605  0.964373
 0.156411   0.46562   0.841971  0.466243     0.0949366  0.919987   0.618168
 0.983644   0.234543  0.285416  0.822095     0.832267   0.483606   0.622308
 0.238802   0.889805  0.183117  0.637834     0.178647   0.0583783  0.593469
 0.0169004  0.628306  0.864698  0.838922     0.809376   0.615039   0.853035

In [5]:
y = rand(Float64, (10,10))

10×10 Matrix{Float64}:
 0.280114  0.938794   0.864442   0.17426   …  0.184621   0.512075   0.746796
 0.317711  0.882983   0.462216   0.941366     0.818814   0.632436   0.913017
 0.187471  0.333949   0.945336   0.419685     0.0521051  0.310476   0.298664
 0.300338  0.767666   0.904996   0.544848     0.206923   0.953015   0.326638
 0.969066  0.25321    0.0734853  0.228423     0.595521   0.972847   0.971822
 0.835451  0.490761   0.708086   0.331338  …  0.337146   0.176568   0.778562
 0.925883  0.0999027  0.246501   0.116781     0.835158   0.596161   0.670253
 0.567613  0.51434    0.388812   0.151809     0.813722   0.822223   0.600006
 0.240768  0.122828   0.560033   0.166212     0.0984176  0.0223261  0.894314
 0.523936  0.942125   0.527515   0.400411     0.725032   0.524074   0.443382

In [6]:
c = zeros(10,10)

10×10 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

In [17]:
@time LinearAlgebra.mul!(c,x,y)

  0.000017 seconds


10×10 Matrix{Float64}:
 3.22621  3.13445  2.87076  1.85264  …  2.40015  3.05483  3.59668  3.85235
 2.4042   2.8469   3.05917  1.78756     2.27488  2.03665  2.85695  3.72393
 2.83133  2.89244  2.94395  1.95372     2.43624  2.6651   2.90179  3.8115
 2.16538  3.02051  3.04253  1.75687     2.1775   2.17015  2.96001  2.74671
 3.12866  3.32841  3.39587  2.1978      2.624    2.97386  3.38604  4.47369
 3.15279  3.31874  2.96816  1.78642  …  2.2477   2.93025  3.82722  3.55048
 2.87679  2.3715   2.95367  1.86289     2.45911  2.44523  2.77976  3.64148
 2.57947  3.40562  3.49496  1.75681     2.17555  2.23092  3.01873  3.46689
 2.95008  2.7887   2.39835  2.04747     2.18719  2.76351  3.18867  3.43428
 3.21952  3.24508  3.62513  2.34077     2.76349  3.1392   3.49783  3.83868

In [10]:
@time x*y

  0.007737 seconds (6.97 k allocations: 411.179 KiB, 94.96% compilation time)


10×10 Matrix{Float64}:
 3.22621  3.13445  2.87076  1.85264  …  2.40015  3.05483  3.59668  3.85235
 2.4042   2.8469   3.05917  1.78756     2.27488  2.03665  2.85695  3.72393
 2.83133  2.89244  2.94395  1.95372     2.43624  2.6651   2.90179  3.8115
 2.16538  3.02051  3.04253  1.75687     2.1775   2.17015  2.96001  2.74671
 3.12866  3.32841  3.39587  2.1978      2.624    2.97386  3.38604  4.47369
 3.15279  3.31874  2.96816  1.78642  …  2.2477   2.93025  3.82722  3.55048
 2.87679  2.3715   2.95367  1.86289     2.45911  2.44523  2.77976  3.64148
 2.57947  3.40562  3.49496  1.75681     2.17555  2.23092  3.01873  3.46689
 2.95008  2.7887   2.39835  2.04747     2.18719  2.76351  3.18867  3.43428
 3.21952  3.24508  3.62513  2.34077     2.76349  3.1392   3.49783  3.83868